services:
  backend:
    container_name: books-backend
    build: .
    ports:
      - "${APP_PORT:-3000}:${APP_PORT:-3000}"
    env_file:
      - .env.production
    depends_on:
      - postgres
    networks:
      - books-net

  postgres:
    container_name: books-db
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env.production
    volumes:
      - postgres:/var/lib/postgresql
    networks:
      - books-net

volumes:
  postgres:

networks:
  books-net:
    driver: bridge
